// utils/pdfExport.js
// AI ke CV/Resume response ko PDF mein convert karta hai

export async function downloadAsPDF(content, filename = 'NexusAI-CV.pdf') {
    // html2pdf dynamic import
    const html2pdf = (await import('html2pdf.js')).default

    // Markdown ko clean HTML mein convert karo
    const html = markdownToHTML(content)

    // PDF wrapper div banao
    const element = document.createElement('div')
    element.innerHTML = `
    <div style="
      font-family: 'Segoe UI', Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      color: #1a1a2e;
      background: #ffffff;
      font-size: 13px;
      line-height: 1.6;
    ">
      <!-- Header -->
      <div style="
        text-align: center;
        border-bottom: 2px solid #3b82f6;
        padding-bottom: 16px;
        margin-bottom: 24px;
      ">
        <div style="
          font-size: 10px;
          color: #3b82f6;
          font-weight: 600;
          letter-spacing: 2px;
          text-transform: uppercase;
          margin-bottom: 4px;
        ">Generated by NexusAI</div>
      </div>

      <!-- Content -->
      <div class="cv-content">
        ${html}
      </div>

      <!-- Footer -->
      <div style="
        margin-top: 32px;
        padding-top: 12px;
        border-top: 1px solid #e5e7eb;
        text-align: center;
        font-size: 10px;
        color: #9ca3af;
      ">
        Created with NexusAI · nexusai-2026.netlify.app
      </div>
    </div>
  `

    // Styles inject karo
    const style = document.createElement('style')
    style.textContent = `
    .cv-content h1 {
      font-size: 22px; font-weight: 700; color: #1a1a2e;
      margin: 0 0 4px; text-align: center;
    }
    .cv-content h2 {
      font-size: 14px; font-weight: 700; color: #3b82f6;
      margin: 20px 0 8px; text-transform: uppercase;
      letter-spacing: 1px; border-bottom: 1px solid #dbeafe;
      padding-bottom: 4px;
    }
    .cv-content h3 {
      font-size: 13px; font-weight: 600; color: #1a1a2e;
      margin: 12px 0 4px;
    }
    .cv-content p { margin: 0 0 8px; color: #374151; }
    .cv-content ul { margin: 4px 0 8px; padding-left: 18px; }
    .cv-content li { margin-bottom: 3px; color: #374151; }
    .cv-content strong { color: #1a1a2e; font-weight: 600; }
    .cv-content em { color: #6b7280; font-style: italic; }
    .cv-content hr {
      border: none; border-top: 1px solid #e5e7eb;
      margin: 16px 0;
    }
  `
    element.appendChild(style)
    document.body.appendChild(element)

    // PDF options
    const options = {
        margin: [10, 10, 10, 10],
        filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
            scale: 2,
            useCORS: true,
            letterRendering: true,
        },
        jsPDF: {
            unit: 'mm',
            format: 'a4',
            orientation: 'portrait',
        },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
    }

    try {
        await html2pdf().set(options).from(element).save()
    } finally {
        document.body.removeChild(element)
    }
}

// Simple markdown → HTML converter for PDF
function markdownToHTML(text) {
    if (!text) return ''

    let html = text
        // Escape HTML
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')

        // Headers
        .replace(/^### (.+)$/gm, '<h3>$1</h3>')
        .replace(/^## (.+)$/gm, '<h2>$1</h2>')
        .replace(/^# (.+)$/gm, '<h1>$1</h1>')

        // Bold + Italic
        .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.+?)\*/g, '<em>$1</em>')

        // HR
        .replace(/^---$/gm, '<hr>')

        // Bullet lists
        .replace(/^[\*\-] (.+)$/gm, '<li>$1</li>')

        // Numbered lists
        .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')

        // Wrap consecutive li in ul
        .replace(/(<li>.*<\/li>\n?)+/gs, (match) => `<ul>${match}</ul>`)

        // Paragraphs
        .replace(/\n\n/g, '</p><p>')
        .replace(/\n/g, '<br>')

    return `<p>${html}</p>`
        .replace(/<p>(<h[123]>)/g, '$1')
        .replace(/(<\/h[123]>)<\/p>/g, '$1')
        .replace(/<p>(<ul>)/g, '$1')
        .replace(/(<\/ul>)<\/p>/g, '$1')
        .replace(/<p>(<hr>)<\/p>/g, '$1')
        .replace(/<p><\/p>/g, '')
}

// Check karo ke message mein CV/Resume content hai ya nahi
export function isResumeContent(content) {
    const keywords = [
        'resume', 'cv', 'curriculum vitae',
        'work experience', 'education', 'skills',
        'objective', 'summary', 'contact',
        'experience', 'qualification',
    ]
    const lower = content.toLowerCase()
    const matchCount = keywords.filter(k => lower.includes(k)).length
    return matchCount >= 3
}
